<!-- File autogenerated by the Paraglide-SvelteKit CLI - Feel free to edit -->
<script lang="ts">
    import { ParaglideJS } from "@inlang/paraglide-sveltekit"
    import { i18n } from "$lib/i18n"
	import { pwaAssetsHead } from "virtual:pwa-assets/head";
	import { pwaInfo } from "virtual:pwa-info";
	import { type Snippet } from 'svelte';
	import {isMobile} from "$lib/runes/page.svelte";
	import {Toaster} from "svelte-sonner";

	let webManifest = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');

	let { children }: { children?: Snippet } = $props();
</script>



<svelte:head>
	{#if pwaAssetsHead.themeColor}
		<meta name="theme-color" content={pwaAssetsHead.themeColor.content} />
	{/if}

	{#each pwaAssetsHead.links as link}
		<link {...link} />
	{/each}

	{@html webManifest}
</svelte:head>



{#await import('$lib/PWAReloadPrompt.svelte') then { default: ReloadPrompt }}
	<ReloadPrompt />
{/await}



<Toaster
	position={isMobile.value ? "top-center" : "bottom-right"}
	class="h-52 overflow-visible md:flex md:justify-end"
/>


<ParaglideJS {i18n}>
	{@render children?.()}
</ParaglideJS>
