export type CustomerType = {
	customerNodeCode: null,
	name: "",
	companyName: "",
	street: "",
	city: "",
	postalCode: "",
	countryCode: "",
	ico: "",
	dic: "",
	icDph: "",
	paymentTypeCode: "",
	dueDays: null,
	invoiceCopies: null,
	deliveryNoteCopies: null,
	customerStoreCode: null,
	consignmentSaleEnabled: false,
	isReturnAllowed: false,
	useAssortedEanCodes: false,
	customerAlbiCode: null,
	keyCustomerTypeId: null,
	creditLimit: null,
	unpaidAmount: null,
	lastPaymentDate: null,
	email: "",
	ediInboxEanCode: null,
	ediInboxEanCodeForInvoice: null,
	customerStoreEan: null,
	sendDeliveryNoteViaEdi: false,
	sendInvoiceViaEdi: false,
	sendCreditNoteViaEdi: false,
	useDiacriticalMarksInEdiDocuments: false,
	consignmentOutputCheck: false,
	isChargedWithoutVat: false,
	claimNotificationDisabled: false,
	isBadPayer: false,
	tradeLicenseReceived: false,
	printPricesOnDeliveryNote: false,
	allwaysAllowOrdering: false,
	b2BeshopEnabled: false,
	isApproved: false,
	sendInvoiceAfterApproval: false,
	invoiceConfirmationNotRequired: false,
	isBlocked: false,
	contractReceived: false
}


export type CustomerAddressType = {
	id: number,
	customerNodeCode: number,
	customerName: string,
	name: string,
	customerAddressCode: string,
	companyName: string,
	street: string,
	city: string,
	postalCode: string,
	countryCode: string,
	note: string,
	paymentTypeCode: string,
	dueDays: number,
	invoiceCopies: number,
	deliveryNoteCopies: number,
	customerRank: string,
	retailStoreTypeId: string,
	customerStoreCode: string,
	customerStoreEan: string,
	packingNote: string,
	consignmentSaleEnabled: boolean,
	isReturnAllowed: boolean,
	isForConsignmentReturn: boolean,
	useAssortedEanCodes: boolean,
	pickingBoxPacking: boolean,
	splitOrderByFood: boolean,
	dealerCode: string,
	areaCode: string,
	areaId: string
}

export type CustomerContactType = {
	isDefault: boolean,
	enabled: boolean,
	name: string|null,
	surname: string|null,
	mobile: string|null,
	phone: string|null,
	email: string|null,
	note: string|null,
	pdfInvoice: boolean,
	pdfDeliveryNote: boolean,
	csvInvoice: boolean,
	csvDeliveryNote: boolean,
	consignmentReturnInfo: boolean,
	consignmentInfo: boolean,
	carrierInfo: boolean
}
