import { pageCompact } from "$lib/runes/page.svelte";


export const themeAlbiBlueParams = {
	accentColor: "#03BFD7",
	advancedFilterBuilderButtonBarBorder: true,
	advancedFilterBuilderColumnPillColor: "#D0FA9C",
	advancedFilterBuilderJoinPillColor: "#FFCAE5",
	advancedFilterBuilderOptionPillColor: "#FEFF86",
	advancedFilterBuilderValuePillColor: "#A4F6FD",
	borderColor: "#E1E7EF",
	borderRadius: 6,
	cellHorizontalPaddingScale: 0.8,
	columnBorder: true,
	columnDropCellBorder: true,
	dialogBorder: true,
	filterToolPanelGroupIndent: 61,
	footerRowBorder: true,
	foregroundColor: "#073545",
	headerBackgroundColor: "#FFFFFF",
	headerColumnBorder: false,
	headerColumnResizeHandleColor: "#E1E7EF",
	headerColumnResizeHandleWidth: 2,
	headerFontSize: 12,
	headerHeight: 32,
	headerFontWeight: 700,
	headerRowBorder: true,
	headerVerticalPaddingScale: 1,
	checkboxBorderRadius: 4,
	checkboxBorderWidth: 1,
	checkboxCheckedShapeColor: "#FFFFFF",
	iconSize: 16,
	inputBackgroundColor: "#FFFFFF",
	inputFocusBorder: true,
	inputPaddingStart: 6,
	listItemHeight: 22,
	menuBackgroundColor: "#FFFFFF",
	menuSeparatorColor: "#E1E7EF",
	oddRowBackgroundColor: "#FAFAFA",
	panelBackgroundColor: "#FFFFFF",
	panelTitleBarBackgroundColor: "#FFFFFF",
	panelTitleBarBorder: true,
	pinnedColumnBorder: true,
	pinnedRowBorder: true,
	rowBorder: true,
	rowHoverColor: "#03BFD714",
	selectCellBorder: false,
	selectedRowBackgroundColor: "rgba(255,237,190,0.32)",
	sideBarBackgroundColor: "#FFFFFF",
	spacing: pageCompact.value ? 2 : 5,
	tabBottomPadding: 6,
	tabHoverBackgroundColor: "#00000000",
	toolPanelSeparatorBorder: true,
	wrapperBorder: false,
	wrapperBorderRadius: 8
}
