export enum RibbonActionEnum {
	NEW = "new",
	DELETE = "delete",
	EDIT = "edit",
	FILL_DOWN = "fill-down",
	SAVE = "save",
	LOAD = "load",
	PRINT = "print",
	EXPORT_CHOICE = "export-choice",
	EXPORT_EXCEL_DATA = "export-excel-data",
	EXPORT_EXCEL_HEADERS = "export-excel-headers",
	EXPORT_PDF = "export-pdf",
	EXPORT_CSV = "export-csv",
	GROUP_EXPORT = "group-export",
	IMPORT = "import",
	STATISTICS = "statistics",
	FILTER_QUICK = "filter-quick",
	FILTER_OUT_OF_RANGE = "filter-out-of-range",
	FILTER_IN_RANGE = "filter-in-range",
	FILTER_UNDO = "filter-undo",
	FILTER_REMOVE = "filter-remove",
	SAVE_FILTERS = "save-filters",
	MY_FILTERS = "my-filters",
	SAVE_PRESET = "save-preset",
	MY_PRESETS = "my-presets",
	UNKNOWN = "unknown",
}
